name: Go Test Workflow

on: [push, pull_request]

jobs:
  test:
    name: Run Go Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go environment
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Download Go modules
        run: go mod download

      - name: Run tests
        run: go test ./...
